hpi_quotedb/quotedb/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.quotes, {"order" : "newest"}, name="index"),

    url(r'^quote/submit$', views.submit_quote, name="submit_quote"),
    #url(r'^quote/report/(?P<pk>[0-9]+)$', views.report_quote),
    url(r'^quote/vote/(?P<pk>[0-9]+)/(?P<vote>-1|0|1)$', views.vote_quote, name="vote_quote"),

    url(r'^quotes/(?P<pk>[0-9]+)$', views.single_quote, name="single_quote"),
    url(r'^quotes/random$', views.random_quote, name="random_quote"),
    url(r'^quotes$', views.quotes),
    url(r'^quotes/(?P<order>newest|top)$', views.quotes, name="quotes"),
    url(r'^quotes/tag/(?P<tag>.*)$', views.quotes_by_tag, name="quotes_by_tag"),
]

hpi_quotedb/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin
from . quotedb import urls as quotedb_urls

urlpatterns = [
    url(r'^' + settings.SERVER_BASE_PATH + r'admin/', include(admin.site.urls)),
    url(r'^' + settings.SERVER_BASE_PATH, include(quotedb_urls, namespace="quotedb")),
]

hpi_quotedb/quotedb/models.py
from django.db import models
from django.utils import html

import hashlib
import random
import string

from .util import get_username

# Create your models here.

def random_string(length):
    return "".join([ random.choice(string.ascii_letters + string.digits) for i in range(length) ])

class Tag(models.Model):
    class Meta:
        ordering = ["name"]

    name = models.CharField(max_length=64, blank=False, unique=True)

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse("quotedb:quotes_by_tag", kwargs={"tag" : self.name})

    def hashtag(self):
        return html.mark_safe("<a href='%s'>#%s</a>" % (self.get_absolute_url(), html.escape(self.name)))

    def __str__(self):
        return "#%s" % self.name

    @staticmethod
    def get_tag_cloud():
        tags = Tag.objects.all()
        cloud = []
        for tag in tags:
            # TODO automatically delete where count=0 ?
            count = Quote.objects.filter(tags=tag, visible=True).count()
            if count != 0:
                cloud.append((tag, count))
        cloud.sort(reverse=True, key=lambda t: t[1])
        return cloud

class VoteKey(models.Model):
    key = models.CharField(blank=True, default="", max_length=255)

    @staticmethod
    def get():
        keys = VoteKey.objects.all()
        if keys.count() == 0:
            return VoteKey.objects.create(key=random_string(16)).key
        elif keys.count() == 1:
            return keys[0].key
        else:
            # there may be only one key
            key = keys[0]
            # delete all except one
            VoteKey.objects.all().exclude(pk=key.pk)
            return key.key

class Vote(models.Model):
    quote = models.ForeignKey("Quote")
    value = models.IntegerField(default=1)
    hash = models.CharField(blank=True, default="", max_length=255)

    @staticmethod
    def generate_vote_hash(quote, user):
        string = str(quote.pk) + user + VoteKey.get()
        return hashlib.md5(string.encode("utf-8")).hexdigest()

class Quote(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    text = models.TextField(default="")
    tags = models.ManyToManyField(Tag, blank=True)
    visible = models.BooleanField(default=False)
    voting = models.IntegerField(default=0)

    def update_votes(self):
        votes = Vote.objects.all().filter(quote=self)
        old_voting = self.voting
        self.voting = votes.filter(value=1).count() - votes.filter(value=-1).count()
        if old_voting != self.voting:
            self.save()

    def process_voted(self, request):
        hash = Vote.generate_vote_hash(self, get_username(request))
        votes = Vote.objects.all().filter(quote=self, hash=hash)
        if votes.count() == 0:
            self.voted = 0
        else:
            self.voted = votes[0].value
        return self
    
    @property
    def upvotes(self):
        return Vote.objects.filter(quote=self, value=1).count()

    @property
    def downvotes(self):
        return Vote.objects.filter(quote=self, value=-1).count()

hpi_quotedb/quotedb/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.conf import settings
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.forms import ModelForm, CharField, ValidationError
from django.utils.translation import ugettext as _
from .models import Tag, Quote, Vote
from .util import get_username

import random

# Create your views here.

class QuoteForm(ModelForm):
    class Meta:
        model = Quote
        fields = ["text"]

    tags = CharField(max_length=255, required=False)

    def clean_tags(self):
        tags = self.cleaned_data.get("tags", "")
        parsed_tags = set()
        for tag in tags.split(" "):
            tag = tag.strip().replace("#", "")
            if not tag:
                continue
            if not tag.isalnum():
                raise ValidationError(_("Invalid tag value (must be alphanumeric): %(value)s"), code="invalid", params={"value" : tag})
            parsed_tags.add(tag)
        return parsed_tags

    def save(self, commit=True):
        instance = super(QuoteForm, self).save(commit=commit)
        for tag in self.cleaned_data.get("tags", set()):
            instance.tags.add(Tag.objects.get_or_create(name=tag)[0])
        if commit:
            instance.save()
        return instance

def submit_quote(request):
    form = None
    if request.method == "POST":
        form = QuoteForm(request.POST)
        if form.is_valid():
            instance = form.save()
            instance.visible = not settings.QUOTEDB_VERIFY_QUOTES
            instance.save()
            messages.info(request, settings.QUOTEDB_POST_SUBMIT_NOTICE)
            # TODO inform admin about new quote and review
            return redirect("quotedb:quotes", order="newest")
    else:
        form = QuoteForm()
    context = {"form" : form, "current_page" : "submit"}
    return render(request, "quote/submit.html", context)

def vote_quote(request, pk, vote):
    quote = get_object_or_404(Quote, visible=True, pk=pk)

    hash = Vote.generate_vote_hash(quote, get_username(request))
    votes = Vote.objects.all().filter(quote=quote, hash=hash)
    if votes.count() == 0:
        Vote.objects.create(quote=quote, value=vote, hash=hash)
    else:
        Vote.objects.all().filter(quote=quote, hash=hash).update(value=vote)
    quote.update_votes()
    return redirect(request.GET.get("return"))

def single_quote(request, pk):
    context = {"quote" : get_object_or_404(Quote, visible=True, pk=pk).process_voted(request), "current_page" : "single"}
    return render(request, "quotes/quotes.html", context)

def random_quote(request):
    count = Quote.objects.all().filter(visible=True).count()
    quote = get_list_or_404(Quote, visible=True)[random.randint(0, count - 1)].process_voted(request)
    context = {"title" : "Random quote", "quote" : quote, "current_page" : "random"}
    return render(request, "quotes/quotes.html", context)

def show_quotes(request, redirect_if_invalid, title, current_page, quote_list):
    paginator = Paginator(quote_list, settings.QUOTEDB_QUOTES_PER_PAGE)
    page = request.GET.get("page")
    quotes = None
    try:
        quotes = paginator.page(page)
    except PageNotAnInteger:
        response = redirect_if_invalid
        response["Location"] += "?page=1"
        return response
    except EmptyPage:
        response = redirect_if_invalid
        response["Location"] += "?page=%d" % paginator.num_pages
        return response
    context = {"title" : title, "quotes" : quotes, "current_page" : current_page}
    if type(current_page) == tuple:
        context.update({"current_page" : "tag", "current_tag" : current_page[1]})
    return render(request, "quotes/quotes.html", context)

def quotes(request, order="newest"):
    title = ""
    quote_list = Quote.objects.all().filter(visible=True)
    if order == "newest":
        title = "Newest quotes"
        quote_list = quote_list.order_by("-date")
    elif order == "top":
        title = "Top quotes"
        quote_list = quote_list.order_by("-voting")
    for quote in quote_list:
        quote.process_voted(request)
    return show_quotes(request, redirect("quotedb:quotes", order=order), title, order, quote_list)

def quotes_by_tag(request, tag):
    tag = get_object_or_404(Tag, name=tag)
    title = "Quotes with tag #%s" % tag.name
    quotes = Quote.objects.filter(tags=tag)
    for quote in quotes:
        quote.process_voted(request)
    return show_quotes(request, redirect("quotedb:quotes_by_tag", tag=tag.name), title, ("tag", tag.name), quotes)

hpi_quotedb/quotedb/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>{{ QUOTEDB_TITLE }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <!--<link href="starter-template.css" rel="stylesheet">-->
    <link href="{% static "css/style.css" %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{% static "js/ie-emulation-modes-warning.js" %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="{% url "quotedb:index" %}">{{ QUOTEDB_TITLE }}</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <!--<ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>-->
          <ul class="nav navbar-nav navbar-right">
            {% if QUOTEDB_USER %}
            <li><a href="#">(Debug) Username: {{ QUOTEDB_USER }}</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="btn-toolbar" role="toolbar">
                    <div class="btn-group" role="group">
                        <a href="{% url "quotedb:submit_quote" %}" role="button" class="btn btn-default {% if current_page == "submit" %}active{% endif %}">Submit quote</a>
                        <a href="{% url "quotedb:quotes" order="newest" %}" role="button" class="btn btn-default {% if current_page == "newest" %}active{% endif %}">Newest quotes</a>
                        <a href="{% url "quotedb:quotes" order="top" %}" role="button" class="btn btn-default {% if current_page == "top" %}active{% endif %}">Top quotes</a>
                        <a href="{% url "quotedb:random_quote" %}" role="button" class="btn btn-default {% if current_page == "random" %}active{% endif %}">Random quote</a>
                    </div>
                </div>

                <div style="padding-top: 20px"></div>
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                {% endfor %}

                {% block content %}
                {% endblock %}
            </div>

            <div class="col-md-4">
                <div class="panel panel-default panel-info">
                    <div class="panel-heading">Quotes by tag</div>
                    <div class="panel-body">
                        {% for tag, count in tagcloud %}
                        {% if current_page == "tag" and current_tag == tag.name %}<b>{% endif %}
                        <a href="{{ tag.get_absolute_url }}">#{{ tag.name }} ({{ count }})</a>
                        {% if current_page == "tag" and current_tag == tag.name %}</b>{% endif %}
                        {% if not forloop.last %},{% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>

    </div><!-- /.container -->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static "js/ie10-viewport-bug-workaround.js" %}"></script>
  </body>
</html>

hpi_quotedb/quotedb/templates/general/index.html
{% extends "base.html" %}

{% block content %}
<div class="row">
    <h1>Hello World!</h1>
</div>

{% include "quotes/list_quotes.html" with quotes=quotes %}
{% endblock %}

hpi_quotedb/quotedb/templates/quote/submit.html
{% extends "base.html" %}
{% load bootstrap %}

<h2>Submit quote</h2>

{% block content %}
<script>
function getTags() {
    var text = $("#id_tags").val();
    var split = text.split(" ");
    var tags = [];
    for(var i = 0; i < split.length; i++) {
        var tag = split[i].trim().replace("#", "");
        if (tag.length != 0 && tags.indexOf(tag) == -1)
            tags.push(tag);
    }
    return tags;
}

function setTags(tags) {
    var text = tags.join(" #");
    if (text.length != 0)
        text = "#"  + text;
    $("#id_tags").val(text);
}

window.addEventListener("load", function() {
    $("a.tag-helper").click(function() {
        var tag = $(this).data("tag");
        var tags = getTags();
        if (tags.indexOf(tag) == -1) {
            tags.push(tag);
        } else {
            tags.splice(tags.indexOf(tag), 1);
        }
        setTags(tags);
    });

    $("#id_tags").focusout(function() {
        setTags(getTags());
    });
});
</script>

{% if QUOTEDB_PRE_SUBMIT_NOTICE %}
<div class="alert alert-info" role="alert">
    {{ QUOTEDB_PRE_SUBMIT_NOTICE|safe }}
</div>
{% endif %}

<form action="{% url "quotedb:submit_quote" %}" method="POST" role="form">
    {% csrf_token %}
    {{ form|bootstrap }}
    <span class="help-block">
        Tags:
        {% for tag, count in tagcloud %}
            <a class="tag-helper" href="#" data-tag="{{ tag.name }}">#{{ tag.name }} ({{ count }})</a>{% if not forloop.last %},{% endif %}
        {% endfor %}

    </span>
    <input type="submit" value="Submit" />
</form>
{% endblock %}

hpi_quotedb/quotedb/templates/quotes/list_quotes.html
{% for quote in quotes %}
{% include "quotes/quote.html" with quote=quote %}
{% endfor %}

hpi_quotedb/quotedb/templates/quotes/quote.html
<!--
<div class="quote">
    <div><a href="{% url "quotedb:single_quote" pk=quote.pk %}">{{ quote.date }}</a></div>
    <div>{{ quote.text|linebreaksbr }}</div>
    <div>
        {% for tag in quote.tags.all %}
            {% if forloop.first %}<br />{% endif %}
            {{ tag.hashtag }}
        {% endfor %}
    </div>
    <div>
        Upvotes: {{ quote.upvotes }},
        Downvotes: {{ quote.downvotes }}

        {% if quote.voted == 1 %}
          <a href="{% url "quotedb:vote_quote" pk=quote.pk vote="0" %}?return={{ request.get_full_path|urlencode }}"><b>+1</b></a>
        {% else %}
          <a href="{% url "quotedb:vote_quote" pk=quote.pk vote="1" %}?return={{ request.get_full_path|urlencode }}">+1</a>
        {% endif %}

        {% if quote.voted == -1 %}
          <a href="{% url "quotedb:vote_quote" pk=quote.pk vote="0" %}?return={{ request.get_full_path|urlencode }}"><b>-1</b></a>
        {% else %}
          <a href="{% url "quotedb:vote_quote" pk=quote.pk vote="-1" %}?return={{ request.get_full_path|urlencode }}">-1</a>
        {% endif %}
    </div>
</div>
-->

<style>
.text-success a:link, .text-danger a:link, .text-success a:visited, .text-danger a:visited {
    color: inherit;
}
</style>

<div class="panel panel-default">
    <div class="panel-heading">
        <span class="pull-right">
            <span class="text-success">
                {% if quote.voted == 1 %}
                    <a href="{% url "quotedb:vote_quote" pk=quote.pk vote="0" %}?return={{ request.get_full_path|urlencode }}"><b>
                {% else %}
                    <a href="{% url "quotedb:vote_quote" pk=quote.pk vote="1" %}?return={{ request.get_full_path|urlencode }}">
                {% endif %}
                <span class="glyphicon glyphicon-chevron-up"></span> {{ quote.upvotes }}
                {% if quote.voted == 1 %}
                    </b></a>
                {% else %}
                    </a>
                {% endif %}
            </span>
            <span class="text-danger">
                {% if quote.voted == -1 %}
                    <a href="{% url "quotedb:vote_quote" pk=quote.pk vote="0" %}?return={{ request.get_full_path|urlencode }}"><b>
                {% else %}
                    <a href="{% url "quotedb:vote_quote" pk=quote.pk vote="-1" %}?return={{ request.get_full_path|urlencode }}">
                {% endif %}
                <span class="glyphicon glyphicon-chevron-down"></span> {{ quote.downvotes }}
                {% if quote.voted == -1 %}
                    </b></a>
                {% else %}
                    </a>
                {% endif %}
            </span>
        </span>
        <a href="{% url "quotedb:single_quote" pk=quote.pk %}">{{ quote.date }}</a>
    </div>
    <div class="panel-body">
        <div>
            {{ quote.text|linebreaksbr }}
        </div>

        {% if quote.tags.all.count != 0 %}
        <div style="margin-top: 20px">
            {% for tag in quote.tags.all %}
                {{ tag.hashtag }}
            {% endfor %}
        </div>
        {% endif %}
    </div>
</div>

hpi_quotedb/quotedb/templates/quotes/quotes.html
{% extends "base.html"  %}

{% block content %}
{% if quote %}
    {% include "quotes/quote.html" with quote=quote %}
{% else %}
    {% include "quotes/list_quotes.html" with quotes=quotes %}

    <div class="pagination">
        <span class="step-links">
            <nav>
                <ul class="pager">
                    <li class="{% if not quotes.has_previous %}disabled{% endif %}"><a href="{% if quotes.has_previous %}?page={{ quotes.previous_page_number }}{% endif %}"><span aria-hidden="true">&larr;</span> Previous</a></li>
                    <li class="disabled"><a style="cursor: default">Page {{ quotes.number }} of {{ quotes.paginator.num_pages }}</a></li>
                    <li class="{% if not quotes.has_next %}disabled{% endif %}"><a href="{% if quotes.has_next %}?page={{ quotes.next_page_number }}{% endif %}">Next <span aria-hidden="true">&rarr;</span></a></li>
                </ul>
            </nav>
        </span>
    </div>
{% endif %}
{% endblock %}